// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_alert_recipients.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"
)

const claimActiveAlertRecipient = `-- name: ClaimActiveAlertRecipient :one
INSERT INTO active_alert_recipients (
	fingerprint, recipient_id, status, message_id,
	claim_owner, claimed_at, posted_at, last_update)
VALUES ($1, $2, $3, '', $4, $5, NULL, $6)
ON CONFLICT(fingerprint, recipient_id) DO NOTHING
RETURNING fingerprint, status, recipient_id, message_id, claim_owner, claimed_at, posted_at, last_update
`

type ClaimActiveAlertRecipientParams struct {
	Fingerprint string
	RecipientID string
	Status      string
	ClaimOwner  string
	ClaimedAt   sql.NullTime
	LastUpdate  time.Time
}

// ClaimActiveAlertRecipient takes the right to send or update the message for
// one recipient. A row comes back only when the claim is ours; see
// ClaimActiveAlert for what a caller does with the two ways this can come back
// empty.
func (q *Queries) ClaimActiveAlertRecipient(ctx context.Context, arg ClaimActiveAlertRecipientParams) (ActiveAlertRecipient, error) {
	row := q.db.QueryRowContext(ctx, claimActiveAlertRecipient,
		arg.Fingerprint,
		arg.RecipientID,
		arg.Status,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.LastUpdate,
	)
	var i ActiveAlertRecipient
	err := row.Scan(
		&i.Fingerprint,
		&i.Status,
		&i.RecipientID,
		&i.MessageID,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.PostedAt,
		&i.LastUpdate,
	)
	return i, err
}

const completeActiveAlertRecipientClaim = `-- name: CompleteActiveAlertRecipientClaim :one
INSERT INTO active_alert_recipients (
	fingerprint, recipient_id, status, message_id,
	claim_owner, claimed_at, posted_at, last_update)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(fingerprint, recipient_id) DO UPDATE SET
	message_id  = excluded.message_id,
	posted_at   = excluded.posted_at,
	status      = excluded.status,
	last_update = excluded.last_update
WHERE active_alert_recipients.posted_at IS NULL
  AND active_alert_recipients.claim_owner = excluded.claim_owner
RETURNING message_id
`

type CompleteActiveAlertRecipientClaimParams struct {
	Fingerprint string
	RecipientID string
	Status      string
	MessageID   string
	ClaimOwner  string
	ClaimedAt   sql.NullTime
	PostedAt    sql.NullTime
	LastUpdate  time.Time
}

// CompleteActiveAlertRecipientClaim records the message the claim produced.
// See CompleteActiveAlertClaim: zero rows means somebody else's message is
// recorded under this key, so the one just sent is an orphan.
func (q *Queries) CompleteActiveAlertRecipientClaim(ctx context.Context, arg CompleteActiveAlertRecipientClaimParams) (string, error) {
	row := q.db.QueryRowContext(ctx, completeActiveAlertRecipientClaim,
		arg.Fingerprint,
		arg.RecipientID,
		arg.Status,
		arg.MessageID,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.PostedAt,
		arg.LastUpdate,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const deleteActiveAlertRecipientCard = `-- name: DeleteActiveAlertRecipientCard :exec
DELETE FROM active_alert_recipients
WHERE fingerprint = $1 AND recipient_id = $2 AND message_id = $3
`

type DeleteActiveAlertRecipientCardParams struct {
	Fingerprint string
	RecipientID string
	MessageID   string
}

// DeleteActiveAlertRecipientCard removes the row for one message, and only if
// it is still that message: a resolve that raced a refire must not delete the
// new message's row.
func (q *Queries) DeleteActiveAlertRecipientCard(ctx context.Context, arg DeleteActiveAlertRecipientCardParams) error {
	_, err := q.db.ExecContext(ctx, deleteActiveAlertRecipientCard, arg.Fingerprint, arg.RecipientID, arg.MessageID)
	return err
}

const getActiveAlertRecipient = `-- name: GetActiveAlertRecipient :one
SELECT fingerprint, status, recipient_id, message_id, claim_owner, claimed_at, posted_at, last_update
FROM active_alert_recipients
WHERE fingerprint = $1 AND recipient_id = $2
`

type GetActiveAlertRecipientParams struct {
	Fingerprint string
	RecipientID string
}

func (q *Queries) GetActiveAlertRecipient(ctx context.Context, arg GetActiveAlertRecipientParams) (ActiveAlertRecipient, error) {
	row := q.db.QueryRowContext(ctx, getActiveAlertRecipient, arg.Fingerprint, arg.RecipientID)
	var i ActiveAlertRecipient
	err := row.Scan(
		&i.Fingerprint,
		&i.Status,
		&i.RecipientID,
		&i.MessageID,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.PostedAt,
		&i.LastUpdate,
	)
	return i, err
}

const listActiveAlertRecipients = `-- name: ListActiveAlertRecipients :many
SELECT fingerprint, status, recipient_id, message_id, claim_owner, claimed_at, posted_at, last_update
FROM active_alert_recipients
WHERE fingerprint = $1
ORDER BY recipient_id
`

// ListActiveAlertRecipients returns every message sent for an alert, one per
// recipient it fanned out to, and any claim still in flight.
func (q *Queries) ListActiveAlertRecipients(ctx context.Context, fingerprint string) ([]ActiveAlertRecipient, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlertRecipients, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveAlertRecipient
	for rows.Next() {
		var i ActiveAlertRecipient
		if err := rows.Scan(
			&i.Fingerprint,
			&i.Status,
			&i.RecipientID,
			&i.MessageID,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.PostedAt,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStaleClaimRecipient = `-- name: ReapStaleClaimRecipient :execrows

DELETE FROM active_alert_recipients
WHERE fingerprint = $1 AND recipient_id = $2 AND posted_at IS NULL AND claimed_at <= $3
`

type ReapStaleClaimRecipientParams struct {
	Fingerprint string
	RecipientID string
	ClaimedAt   sql.NullTime
}

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
// ReapStaleClaimRecipient is ReapStaleClaim mirrored for a chat delivery; see
// active_alerts.sql for why it is a statement of its own rather than folded
// into the claim below.
func (q *Queries) ReapStaleClaimRecipient(ctx context.Context, arg ReapStaleClaimRecipientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleClaimRecipient, arg.Fingerprint, arg.RecipientID, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseActiveAlertRecipientClaim = `-- name: ReleaseActiveAlertRecipientClaim :exec
DELETE FROM active_alert_recipients
WHERE fingerprint = $1 AND recipient_id = $2
  AND claim_owner = $3 AND posted_at IS NULL
`

type ReleaseActiveAlertRecipientClaimParams struct {
	Fingerprint string
	RecipientID string
	ClaimOwner  string
}

// ReleaseActiveAlertRecipientClaim hands a claim back when the send failed, so
// the next attempt does not have to wait out the staleness cutoff.
func (q *Queries) ReleaseActiveAlertRecipientClaim(ctx context.Context, arg ReleaseActiveAlertRecipientClaimParams) error {
	_, err := q.db.ExecContext(ctx, releaseActiveAlertRecipientClaim, arg.Fingerprint, arg.RecipientID, arg.ClaimOwner)
	return err
}

const touchActiveAlertRecipient = `-- name: TouchActiveAlertRecipient :exec
UPDATE active_alert_recipients
SET status = $1, last_update = $2
WHERE fingerprint = $3 AND recipient_id = $4 AND message_id = $5
`

type TouchActiveAlertRecipientParams struct {
	Status      string
	LastUpdate  time.Time
	Fingerprint string
	RecipientID string
	MessageID   string
}

// TouchActiveAlertRecipient records that an existing message was updated. It
// matches on the message id, like TouchActiveAlert, so a resolve-then-refire
// cycle does not have its newer row stamped by an update meant for the older
// one. Matching an empty message id against an empty message id is an
// ordinary equality, not a NULL comparison, so a card whose send returned no
// id is still reachable here.
func (q *Queries) TouchActiveAlertRecipient(ctx context.Context, arg TouchActiveAlertRecipientParams) error {
	_, err := q.db.ExecContext(ctx, touchActiveAlertRecipient,
		arg.Status,
		arg.LastUpdate,
		arg.Fingerprint,
		arg.RecipientID,
		arg.MessageID,
	)
	return err
}
