// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package pgdb

import (
	"context"
	"time"
)

const createGrant = `-- name: CreateGrant :exec
INSERT INTO grants (id, role, team_id, channel_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateGrantParams struct {
	ID        string
	Role      string
	TeamID    string
	ChannelID string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) error {
	_, err := q.db.ExecContext(ctx, createGrant,
		arg.ID,
		arg.Role,
		arg.TeamID,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM grants WHERE id = $1
`

func (q *Queries) DeleteGrant(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGrant, id)
	return err
}

const deleteGrantsForRole = `-- name: DeleteGrantsForRole :exec
DELETE FROM grants WHERE role = $1
`

// DeleteGrantsForRole replaces the list-and-filter-in-Go that used to stand
// here. A set delete takes the locks the isolation level needs and cannot
// interleave with another writer's replacement into the union of both.
func (q *Queries) DeleteGrantsForRole(ctx context.Context, role string) error {
	_, err := q.db.ExecContext(ctx, deleteGrantsForRole, role)
	return err
}

const listGrants = `-- name: ListGrants :many

SELECT id, role, team_id, channel_id, created_at, updated_at
FROM grants
ORDER BY role, team_id, channel_id
`

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
func (q *Queries) ListGrants(ctx context.Context) ([]Grant, error) {
	rows, err := q.db.QueryContext(ctx, listGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grant
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.TeamID,
			&i.ChannelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
