// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package pgdb

import (
	"context"
	"time"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO user_group_members (group_id, member_type, member_id, added_by, added_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (group_id, member_type, member_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID    string
	MemberType string
	MemberID   string
	AddedBy    string
	AddedAt    time.Time
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember,
		arg.GroupID,
		arg.MemberType,
		arg.MemberID,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO user_groups (id, name, description, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
`

type CreateGroupParams struct {
	ID          string
	Name        string
	Description string
	CreatedBy   string
	At          time.Time
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.ExecContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.At,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM user_groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGroupMemberships = `-- name: DeleteGroupMemberships :exec
DELETE FROM user_group_members
WHERE group_id = $1 OR (member_type = 'group' AND member_id = $1)
`

// Both directions: the group's own members, and the group as someone's member.
func (q *Queries) DeleteGroupMemberships(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMemberships, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_by, created_at, updated_at
FROM user_groups
WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id string) (UserGroup, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllGroupMembers = `-- name: ListAllGroupMembers :many
SELECT group_id, member_type, member_id, added_by, added_at
FROM user_group_members
ORDER BY group_id, member_type, member_id
`

func (q *Queries) ListAllGroupMembers(ctx context.Context) ([]UserGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listAllGroupMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroupMember
	for rows.Next() {
		var i UserGroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberType,
			&i.MemberID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_id, member_type, member_id, added_by, added_at
FROM user_group_members
WHERE group_id = $1
ORDER BY member_type, member_id
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]UserGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroupMember
	for rows.Next() {
		var i UserGroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberType,
			&i.MemberID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many

SELECT id, name, description, created_by, created_at, updated_at
FROM user_groups
ORDER BY lower(name), id
`

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
func (q *Queries) ListGroups(ctx context.Context) ([]UserGroup, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGroup
	for rows.Next() {
		var i UserGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :execrows
DELETE FROM user_group_members
WHERE group_id = $1 AND member_type = $2 AND member_id = $3
`

type RemoveGroupMemberParams struct {
	GroupID    string
	MemberType string
	MemberID   string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.MemberType, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGroup = `-- name: UpdateGroup :execrows
UPDATE user_groups
SET name = $1, description = $2, updated_at = $3
WHERE id = $4
`

type UpdateGroupParams struct {
	Name        string
	Description string
	At          time.Time
	ID          string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.At,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
