// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"context"
	"time"
)

type Querier interface {
	// ClaimActiveAlert takes the right to post the card for one channel. A row
	// comes back only when the claim is ours; a claim somebody else is still
	// working on, and a row that already carries a card, both leave this returning
	// nothing, and the caller reads the row to find out which.
	ClaimActiveAlert(ctx context.Context, arg ClaimActiveAlertParams) (ActiveAlert, error)
	// CompleteActiveAlertClaim records the card the claim produced. The guard is
	// what makes a lost claim visible: zero rows means somebody else's card is
	// recorded under this key, so the one just posted is an orphan and the caller
	// has to say so rather than overwrite them.
	CompleteActiveAlertClaim(ctx context.Context, arg CompleteActiveAlertClaimParams) (string, error)
	// CountActiveAlerts counts cards, not claims: a claim in flight is not yet
	// something this service is keeping up to date.
	CountActiveAlerts(ctx context.Context) (int64, error)
	CreateDestination(ctx context.Context, arg CreateDestinationParams) error
	CreateGrant(ctx context.Context, arg CreateGrantParams) error
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	CreateLinkFlow(ctx context.Context, arg CreateLinkFlowParams) error
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	CreateLoginFlow(ctx context.Context, arg CreateLoginFlowParams) error
	CreateRecipient(ctx context.Context, arg CreateRecipientParams) error
	CreateRoute(ctx context.Context, arg CreateRouteParams) error
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) error
	// DeleteActiveAlertCard removes the row for one card, and only if it is still
	// that card: a resolve that raced a refire must not delete the new card's row.
	DeleteActiveAlertCard(ctx context.Context, arg DeleteActiveAlertCardParams) error
	DeleteDestination(ctx context.Context, id string) error
	DeleteExpiredLinkFlows(ctx context.Context, expiresAt time.Time) error
	DeleteExpiredLoginFlows(ctx context.Context, expiresAt time.Time) error
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteGrant(ctx context.Context, id string) error
	// DeleteGrantsForRole replaces the list-and-filter-in-Go that used to stand
	// here. A set delete takes the locks the isolation level needs and cannot
	// interleave with another writer's replacement into the union of both.
	DeleteGrantsForRole(ctx context.Context, role string) error
	DeleteRecipient(ctx context.Context, id string) error
	DeleteRoute(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTemplate(ctx context.Context, id string) error
	GetActiveAlert(ctx context.Context, arg GetActiveAlertParams) (ActiveAlert, error)
	GetDestination(ctx context.Context, id string) (Destination, error)
	GetRecipient(ctx context.Context, id string) (Recipient, error)
	// GetRecipientBySubject is how the linking flow finds an existing binding for
	// the person redeeming a code, so re-linking updates their row rather than
	// failing on the unique index.
	GetRecipientBySubject(ctx context.Context, subject string) (Recipient, error)
	GetRoute(ctx context.Context, id string) (Route, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTemplate(ctx context.Context, id string) (Template, error)
	// ListActiveAlerts returns every card posted for an alert, one per channel it
	// fanned out to, and any claim still in flight. The order is stable so that
	// delivery, and its tests, see them the same way every time.
	ListActiveAlerts(ctx context.Context, fingerprint string) ([]ActiveAlert, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	ListDestinations(ctx context.Context) ([]Destination, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	ListGrants(ctx context.Context) ([]Grant, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	ListRecipients(ctx context.Context) ([]Recipient, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	ListRoutes(ctx context.Context) ([]Route, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	ListTemplates(ctx context.Context) ([]Template, error)
	// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
	//
	// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
	// file and run make generate.
	// ReapStaleClaim drops a claim a process took and never completed. It is
	// separate from the claim below rather than a WHERE clause on it because the
	// two need different timestamps -- the cutoff and the new claim's own -- and
	// sqlc's SQLite engine folds two parameters that infer the same column name
	// into one. Two statements in one transaction say the same thing and read
	// better: reap what is dead, then claim what is free.
	ReapStaleClaim(ctx context.Context, arg ReapStaleClaimParams) (int64, error)
	// ReleaseActiveAlertClaim hands a claim back when the post failed, so the next
	// attempt does not have to wait out the staleness cutoff. Deleting is safe
	// because posted_at IS NULL says no card was ever created under it.
	ReleaseActiveAlertClaim(ctx context.Context, arg ReleaseActiveAlertClaimParams) error
	// TakeLinkFlow redeems a code once: the row is gone whether or not it had
	// expired, so a code read over somebody's shoulder and typed twice binds
	// nothing the second time.
	TakeLinkFlow(ctx context.Context, code string) (LinkFlow, error)
	// TakeLoginFlow redeems a state once: the row is gone whether or not it had
	// expired, so a replayed callback finds nothing.
	TakeLoginFlow(ctx context.Context, state string) (LoginFlow, error)
	// TouchActiveAlert records that an existing card was updated. It matches on the
	// message id so that a resolve-then-refire cycle, which replaces the card, does
	// not have its newer row stamped by an update to the older one.
	TouchActiveAlert(ctx context.Context, arg TouchActiveAlertParams) error
	UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error
	// The update deliberately leaves subject alone: it is who this binding belongs
	// to, and moving it would point one person's link at another's alerts. What
	// changes on a re-link is the conversation reference.
	UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) error
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
}

var _ Querier = (*Queries)(nil)
