// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package pgdb

import (
	"context"
	"time"
)

const createRoute = `-- name: CreateRoute :exec
INSERT INTO routes (id, name, parent_id, greedy, label_selector, destination_id, template_id, is_default, priority, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateRouteParams struct {
	ID            string
	Name          string
	ParentID      string
	Greedy        bool
	LabelSelector string
	DestinationID string
	TemplateID    string
	IsDefault     bool
	Priority      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) error {
	_, err := q.db.ExecContext(ctx, createRoute,
		arg.ID,
		arg.Name,
		arg.ParentID,
		arg.Greedy,
		arg.LabelSelector,
		arg.DestinationID,
		arg.TemplateID,
		arg.IsDefault,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, name, parent_id, greedy, label_selector, destination_id, template_id, is_default, priority, created_at, updated_at
FROM routes
WHERE id = $1
`

func (q *Queries) GetRoute(ctx context.Context, id string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.Greedy,
		&i.LabelSelector,
		&i.DestinationID,
		&i.TemplateID,
		&i.IsDefault,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many

SELECT id, name, parent_id, greedy, label_selector, destination_id, template_id, is_default, priority, created_at, updated_at
FROM routes
ORDER BY priority DESC, name
`

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.Greedy,
			&i.LabelSelector,
			&i.DestinationID,
			&i.TemplateID,
			&i.IsDefault,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :exec
UPDATE routes
SET name = $1, parent_id = $2, greedy = $3, label_selector = $4, destination_id = $5, template_id = $6, is_default = $7, priority = $8, updated_at = $9
WHERE id = $10
`

type UpdateRouteParams struct {
	Name          string
	ParentID      string
	Greedy        bool
	LabelSelector string
	DestinationID string
	TemplateID    string
	IsDefault     bool
	Priority      int64
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) error {
	_, err := q.db.ExecContext(ctx, updateRoute,
		arg.Name,
		arg.ParentID,
		arg.Greedy,
		arg.LabelSelector,
		arg.DestinationID,
		arg.TemplateID,
		arg.IsDefault,
		arg.Priority,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
