// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package pgdb

import (
	"context"
	"time"
)

const createTemplate = `-- name: CreateTemplate :exec
INSERT INTO templates (id, name, title, message_text, body, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTemplateParams struct {
	ID          string
	Name        string
	Title       string
	MessageText string
	Body        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTemplate,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.MessageText,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTemplate, id)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT id, name, title, message_text, body, created_at, updated_at
FROM templates
WHERE id = $1
`

func (q *Queries) GetTemplate(ctx context.Context, id string) (Template, error) {
	row := q.db.QueryRowContext(ctx, getTemplate, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Title,
		&i.MessageText,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many

SELECT id, name, title, message_text, body, created_at, updated_at
FROM templates
ORDER BY name
`

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.MessageText,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :exec
UPDATE templates
SET name = $1, title = $2, message_text = $3, body = $4, updated_at = $5
WHERE id = $6
`

type UpdateTemplateParams struct {
	Name        string
	Title       string
	MessageText string
	Body        string
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTemplate,
		arg.Name,
		arg.Title,
		arg.MessageText,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
