// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_endpoints.sql

package pgdb

import (
	"context"
	"time"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :exec
INSERT INTO webhook_endpoints (id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at, template_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateWebhookEndpointParams struct {
	ID            string
	TeamSlug      string
	ChannelSlug   string
	DestinationID string
	TokenHash     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	TemplateID    string
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookEndpoint,
		arg.ID,
		arg.TeamSlug,
		arg.ChannelSlug,
		arg.DestinationID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TemplateID,
	)
	return err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookEndpoint, id)
	return err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at, template_id
FROM webhook_endpoints
WHERE id = $1
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamSlug,
		&i.ChannelSlug,
		&i.DestinationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateID,
	)
	return i, err
}

const getWebhookEndpointBySlug = `-- name: GetWebhookEndpointBySlug :one
SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at, template_id
FROM webhook_endpoints
WHERE team_slug = $1 AND channel_slug = $2
`

type GetWebhookEndpointBySlugParams struct {
	TeamSlug    string
	ChannelSlug string
}

// GetWebhookEndpointBySlug is the request path, turned into a row. It is the
// only lookup a sender can reach, so it matches on the pair alone and leaves
// the token to a constant-time comparison outside SQL.
func (q *Queries) GetWebhookEndpointBySlug(ctx context.Context, arg GetWebhookEndpointBySlugParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpointBySlug, arg.TeamSlug, arg.ChannelSlug)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamSlug,
		&i.ChannelSlug,
		&i.DestinationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TemplateID,
	)
	return i, err
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many

SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at, template_id
FROM webhook_endpoints
ORDER BY team_slug, channel_slug
`

// Code generated from ../sqlite by internal/store/queries/gen. DO NOT EDIT.
//
// The statements are the SQLite ones with ? replaced by $n. Edit the SQLite
// file and run make generate.
func (q *Queries) ListWebhookEndpoints(ctx context.Context) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TeamSlug,
			&i.ChannelSlug,
			&i.DestinationID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TemplateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWebhookEndpointToken = `-- name: RotateWebhookEndpointToken :exec
UPDATE webhook_endpoints
SET token_hash = $1, updated_at = $2
WHERE id = $3
`

type RotateWebhookEndpointTokenParams struct {
	TokenHash string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RotateWebhookEndpointToken(ctx context.Context, arg RotateWebhookEndpointTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateWebhookEndpointToken, arg.TokenHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :exec
UPDATE webhook_endpoints
SET team_slug = $1, channel_slug = $2, destination_id = $3, updated_at = $4, template_id = $5
WHERE id = $6
`

type UpdateWebhookEndpointParams struct {
	TeamSlug      string
	ChannelSlug   string
	DestinationID string
	UpdatedAt     time.Time
	TemplateID    string
	ID            string
}

// The token is written by its own statement, so editing an endpoint cannot
// silently rotate the secret the sender is using.
func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookEndpoint,
		arg.TeamSlug,
		arg.ChannelSlug,
		arg.DestinationID,
		arg.UpdatedAt,
		arg.TemplateID,
		arg.ID,
	)
	return err
}
