// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (id, name, token_hash, created_by, created_at, scope, scoped_token_hash, message_scope)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAccessTokenParams struct {
	ID              string
	Name            string
	TokenHash       string
	CreatedBy       string
	CreatedAt       time.Time
	Scope           string
	ScopedTokenHash sql.NullString
	MessageScope    string
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAccessToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.Scope,
		arg.ScopedTokenHash,
		arg.MessageScope,
	)
	return err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM access_tokens WHERE id = ?
`

func (q *Queries) DeleteAccessToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToken, id)
	return err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, name, token_hash, created_by, created_at, last_used_at, scope, scoped_token_hash, message_scope
FROM access_tokens
WHERE token_hash = ?1 OR scoped_token_hash = ?1
`

// GetAccessTokenByHash is how a webhook request is authenticated. Matching on
// the digest in SQL leaks nothing a timing attack could use: the digest of a
// guess says nothing about the digest of the token.
func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Scope,
		&i.ScopedTokenHash,
		&i.MessageScope,
	)
	return i, err
}

const listAccessTokens = `-- name: ListAccessTokens :many
SELECT id, name, token_hash, created_by, created_at, last_used_at, scope, scoped_token_hash, message_scope
FROM access_tokens
ORDER BY name
`

func (q *Queries) ListAccessTokens(ctx context.Context) ([]AccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listAccessTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Scope,
			&i.ScopedTokenHash,
			&i.MessageScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAccessToken = `-- name: TouchAccessToken :exec
UPDATE access_tokens
SET last_used_at = ?
WHERE id = ?
`

type TouchAccessTokenParams struct {
	LastUsedAt sql.NullTime
	ID         string
}

func (q *Queries) TouchAccessToken(ctx context.Context, arg TouchAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAccessToken, arg.LastUsedAt, arg.ID)
	return err
}
