// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: active_events.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const claimActiveEvent = `-- name: ClaimActiveEvent :one
INSERT INTO active_events (
	event_key, team_id, channel_id, state, message_id,
	claim_owner, claimed_at, posted_at, last_update)
VALUES (?, ?, ?, ?, '', ?, ?, NULL, ?)
ON CONFLICT(event_key, team_id, channel_id) DO NOTHING
RETURNING event_key, state, team_id, channel_id, message_id, claim_owner, claimed_at, posted_at, last_update, conversation_id
`

type ClaimActiveEventParams struct {
	EventKey   string
	TeamID     string
	ChannelID  string
	State      string
	ClaimOwner string
	ClaimedAt  sql.NullTime
	LastUpdate time.Time
}

// ClaimActiveEvent takes the right to post the card for one channel. A row
// comes back only when the claim is ours; a claim somebody else is still
// working on, and a row that already carries a card, both leave this returning
// nothing, and the caller reads the row to find out which.
func (q *Queries) ClaimActiveEvent(ctx context.Context, arg ClaimActiveEventParams) (ActiveEvent, error) {
	row := q.db.QueryRowContext(ctx, claimActiveEvent,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.State,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.LastUpdate,
	)
	var i ActiveEvent
	err := row.Scan(
		&i.EventKey,
		&i.State,
		&i.TeamID,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.PostedAt,
		&i.LastUpdate,
		&i.ConversationID,
	)
	return i, err
}

const completeActiveEventClaim = `-- name: CompleteActiveEventClaim :one
INSERT INTO active_events (
	event_key, team_id, channel_id, state, message_id,
	claim_owner, claimed_at, posted_at, last_update, conversation_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(event_key, team_id, channel_id) DO UPDATE SET
	message_id  = excluded.message_id,
	conversation_id = excluded.conversation_id,
	posted_at   = excluded.posted_at,
	state      = excluded.state,
	last_update = excluded.last_update
WHERE active_events.posted_at IS NULL
  AND active_events.claim_owner = excluded.claim_owner
RETURNING message_id
`

type CompleteActiveEventClaimParams struct {
	EventKey       string
	TeamID         string
	ChannelID      string
	State          string
	MessageID      string
	ClaimOwner     string
	ClaimedAt      sql.NullTime
	PostedAt       sql.NullTime
	LastUpdate     time.Time
	ConversationID string
}

// CompleteActiveEventClaim records the card the claim produced. The guard is
// what makes a lost claim visible: zero rows means somebody else's card is
// recorded under this key, so the one just posted is an orphan and the caller
// has to say so rather than overwrite them.
func (q *Queries) CompleteActiveEventClaim(ctx context.Context, arg CompleteActiveEventClaimParams) (string, error) {
	row := q.db.QueryRowContext(ctx, completeActiveEventClaim,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.State,
		arg.MessageID,
		arg.ClaimOwner,
		arg.ClaimedAt,
		arg.PostedAt,
		arg.LastUpdate,
		arg.ConversationID,
	)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const countActiveEvents = `-- name: CountActiveEvents :one
SELECT COUNT(*) FROM active_events WHERE posted_at IS NOT NULL
`

// CountActiveEvents counts cards, not claims: a claim in flight is not yet
// something this service is keeping up to date.
func (q *Queries) CountActiveEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteActiveEventCard = `-- name: DeleteActiveEventCard :exec
DELETE FROM active_events
WHERE event_key = ? AND team_id = ? AND channel_id = ? AND message_id = ?
`

type DeleteActiveEventCardParams struct {
	EventKey  string
	TeamID    string
	ChannelID string
	MessageID string
}

// DeleteActiveEventCard removes the row for one card, and only if it is still
// that card: a resolve that raced a refire must not delete the new card's row.
func (q *Queries) DeleteActiveEventCard(ctx context.Context, arg DeleteActiveEventCardParams) error {
	_, err := q.db.ExecContext(ctx, deleteActiveEventCard,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.MessageID,
	)
	return err
}

const getActiveEvent = `-- name: GetActiveEvent :one
SELECT event_key, state, team_id, channel_id, message_id, claim_owner, claimed_at, posted_at, last_update, conversation_id
FROM active_events
WHERE event_key = ? AND team_id = ? AND channel_id = ?
`

type GetActiveEventParams struct {
	EventKey  string
	TeamID    string
	ChannelID string
}

func (q *Queries) GetActiveEvent(ctx context.Context, arg GetActiveEventParams) (ActiveEvent, error) {
	row := q.db.QueryRowContext(ctx, getActiveEvent, arg.EventKey, arg.TeamID, arg.ChannelID)
	var i ActiveEvent
	err := row.Scan(
		&i.EventKey,
		&i.State,
		&i.TeamID,
		&i.ChannelID,
		&i.MessageID,
		&i.ClaimOwner,
		&i.ClaimedAt,
		&i.PostedAt,
		&i.LastUpdate,
		&i.ConversationID,
	)
	return i, err
}

const listActiveEvents = `-- name: ListActiveEvents :many
SELECT event_key, state, team_id, channel_id, message_id, claim_owner, claimed_at, posted_at, last_update, conversation_id
FROM active_events
WHERE event_key = ?
ORDER BY team_id, channel_id
`

// ListActiveEvents returns every card posted for an event, one per channel it
// fanned out to, and any claim still in flight. The order is stable so that
// delivery, and its tests, see them the same way every time.
func (q *Queries) ListActiveEvents(ctx context.Context, eventKey string) ([]ActiveEvent, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEvents, eventKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveEvent
	for rows.Next() {
		var i ActiveEvent
		if err := rows.Scan(
			&i.EventKey,
			&i.State,
			&i.TeamID,
			&i.ChannelID,
			&i.MessageID,
			&i.ClaimOwner,
			&i.ClaimedAt,
			&i.PostedAt,
			&i.LastUpdate,
			&i.ConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapStaleClaim = `-- name: ReapStaleClaim :execrows
DELETE FROM active_events
WHERE event_key = ? AND team_id = ? AND channel_id = ? AND posted_at IS NULL AND claimed_at <= ?
`

type ReapStaleClaimParams struct {
	EventKey  string
	TeamID    string
	ChannelID string
	ClaimedAt sql.NullTime
}

// ReapStaleClaim drops a claim a process took and never completed. It is
// separate from the claim below rather than a WHERE clause on it because the
// two need different timestamps -- the cutoff and the new claim's own -- and
// sqlc's SQLite engine folds two parameters that infer the same column name
// into one. Two statements in one transaction say the same thing and read
// better: reap what is dead, then claim what is free.
func (q *Queries) ReapStaleClaim(ctx context.Context, arg ReapStaleClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reapStaleClaim,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.ClaimedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releaseActiveEventClaim = `-- name: ReleaseActiveEventClaim :exec
DELETE FROM active_events
WHERE event_key = ? AND team_id = ? AND channel_id = ?
  AND claim_owner = ? AND posted_at IS NULL
`

type ReleaseActiveEventClaimParams struct {
	EventKey   string
	TeamID     string
	ChannelID  string
	ClaimOwner string
}

// ReleaseActiveEventClaim hands a claim back when the post failed, so the next
// attempt does not have to wait out the staleness cutoff. Deleting is safe
// because posted_at IS NULL says no card was ever created under it.
func (q *Queries) ReleaseActiveEventClaim(ctx context.Context, arg ReleaseActiveEventClaimParams) error {
	_, err := q.db.ExecContext(ctx, releaseActiveEventClaim,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.ClaimOwner,
	)
	return err
}

const touchActiveEvent = `-- name: TouchActiveEvent :exec
UPDATE active_events
SET state = ?, last_update = ?
WHERE event_key = ? AND team_id = ? AND channel_id = ? AND message_id = ?
`

type TouchActiveEventParams struct {
	State      string
	LastUpdate time.Time
	EventKey   string
	TeamID     string
	ChannelID  string
	MessageID  string
}

// TouchActiveEvent records that an existing card was updated. It matches on the
// message id so that a resolve-then-refire cycle, which replaces the card, does
// not have its newer row stamped by an update to the older one.
func (q *Queries) TouchActiveEvent(ctx context.Context, arg TouchActiveEventParams) error {
	_, err := q.db.ExecContext(ctx, touchActiveEvent,
		arg.State,
		arg.LastUpdate,
		arg.EventKey,
		arg.TeamID,
		arg.ChannelID,
		arg.MessageID,
	)
	return err
}
