// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bot_teams.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteBotTeam = `-- name: DeleteBotTeam :exec
DELETE FROM bot_teams WHERE team_id = ?
`

func (q *Queries) DeleteBotTeam(ctx context.Context, teamID string) error {
	_, err := q.db.ExecContext(ctx, deleteBotTeam, teamID)
	return err
}

const getBotTeam = `-- name: GetBotTeam :one
SELECT team_id, tenant_id, service_url, updated_at
FROM bot_teams
WHERE team_id = ?
`

func (q *Queries) GetBotTeam(ctx context.Context, teamID string) (BotTeam, error) {
	row := q.db.QueryRowContext(ctx, getBotTeam, teamID)
	var i BotTeam
	err := row.Scan(
		&i.TeamID,
		&i.TenantID,
		&i.ServiceUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotTeams = `-- name: ListBotTeams :many
SELECT team_id, tenant_id, service_url, updated_at
FROM bot_teams
ORDER BY team_id
`

func (q *Queries) ListBotTeams(ctx context.Context) ([]BotTeam, error) {
	rows, err := q.db.QueryContext(ctx, listBotTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotTeam
	for rows.Next() {
		var i BotTeam
		if err := rows.Scan(
			&i.TeamID,
			&i.TenantID,
			&i.ServiceUrl,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotTeam = `-- name: UpsertBotTeam :exec
INSERT INTO bot_teams (team_id, tenant_id, service_url, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(team_id) DO UPDATE SET
	tenant_id   = excluded.tenant_id,
	service_url = excluded.service_url,
	updated_at  = excluded.updated_at
`

type UpsertBotTeamParams struct {
	TeamID     string
	TenantID   string
	ServiceUrl string
	UpdatedAt  time.Time
}

// UpsertBotTeam records an install, or a newer service URL for one: both come
// from the same authenticated activity, and the latest one wins.
func (q *Queries) UpsertBotTeam(ctx context.Context, arg UpsertBotTeamParams) error {
	_, err := q.db.ExecContext(ctx, upsertBotTeam,
		arg.TeamID,
		arg.TenantID,
		arg.ServiceUrl,
		arg.UpdatedAt,
	)
	return err
}
