// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: destinations.sql

package sqlitedb

import (
	"context"
	"time"
)

const createDestination = `-- name: CreateDestination :exec
INSERT INTO destinations (id, name, team_id, channel_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDestinationParams struct {
	ID        string
	Name      string
	TeamID    string
	ChannelID string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateDestination(ctx context.Context, arg CreateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, createDestination,
		arg.ID,
		arg.Name,
		arg.TeamID,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDestination = `-- name: DeleteDestination :exec
DELETE FROM destinations WHERE id = ?
`

func (q *Queries) DeleteDestination(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDestination, id)
	return err
}

const getDestination = `-- name: GetDestination :one
SELECT id, name, team_id, channel_id, created_at, updated_at
FROM destinations
WHERE id = ?
`

func (q *Queries) GetDestination(ctx context.Context, id string) (Destination, error) {
	row := q.db.QueryRowContext(ctx, getDestination, id)
	var i Destination
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TeamID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDestinations = `-- name: ListDestinations :many
SELECT id, name, team_id, channel_id, created_at, updated_at
FROM destinations
ORDER BY name
`

func (q *Queries) ListDestinations(ctx context.Context) ([]Destination, error) {
	rows, err := q.db.QueryContext(ctx, listDestinations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Destination
	for rows.Next() {
		var i Destination
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamID,
			&i.ChannelID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDestination = `-- name: UpdateDestination :exec
UPDATE destinations
SET name = ?, team_id = ?, channel_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateDestinationParams struct {
	Name      string
	TeamID    string
	ChannelID string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateDestination(ctx context.Context, arg UpdateDestinationParams) error {
	_, err := q.db.ExecContext(ctx, updateDestination,
		arg.Name,
		arg.TeamID,
		arg.ChannelID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
