// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_samples.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteEventSamplesSeenBefore = `-- name: DeleteEventSamplesSeenBefore :execrows
DELETE FROM event_samples WHERE last_seen < ?
`

func (q *Queries) DeleteEventSamplesSeenBefore(ctx context.Context, lastSeen time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventSamplesSeenBefore, lastSeen)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExcessEventSampleValues = `-- name: DeleteExcessEventSampleValues :execrows
DELETE FROM event_samples
WHERE kind = 'label'
	AND (
		SELECT COUNT(*) FROM event_samples AS newer
		WHERE newer.kind = event_samples.kind
			AND newer.key = event_samples.key
			AND (newer.last_seen > event_samples.last_seen
				OR (newer.last_seen = event_samples.last_seen AND newer.value < event_samples.value))
	) >= CAST(?1 AS BIGINT)
`

// Keeps the most recently seen values of each label key and deletes the rest.
// A correlated count rather than a window function in a subquery, because the
// same text has to run on SQLite and Postgres. The tie-break on value makes
// two rows seen at the same instant rank the same way on every run.
func (q *Queries) DeleteExcessEventSampleValues(ctx context.Context, keep int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExcessEventSampleValues, keep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listEventSamples = `-- name: ListEventSamples :many
SELECT kind, key, value, seen_count, first_seen, last_seen
FROM event_samples
ORDER BY kind, key, last_seen DESC, value
LIMIT CAST(?1 AS BIGINT)
`

// The CAST keeps the parameter int64 in both dialects: Postgres would
// otherwise infer int32 for a LIMIT.
func (q *Queries) ListEventSamples(ctx context.Context, maxRows int64) ([]EventSample, error) {
	rows, err := q.db.QueryContext(ctx, listEventSamples, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventSample
	for rows.Next() {
		var i EventSample
		if err := rows.Scan(
			&i.Kind,
			&i.Key,
			&i.Value,
			&i.SeenCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventSample = `-- name: UpsertEventSample :exec
INSERT INTO event_samples (kind, key, value, seen_count, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (kind, key, value) DO UPDATE
SET seen_count = event_samples.seen_count + excluded.seen_count,
	last_seen = CASE WHEN excluded.last_seen > event_samples.last_seen
		THEN excluded.last_seen ELSE event_samples.last_seen END
`

type UpsertEventSampleParams struct {
	Kind      string
	Key       string
	Value     string
	SeenCount int64
	FirstSeen time.Time
	LastSeen  time.Time
}

// Adds to the count rather than replacing it, so replicas sharing one
// database each contribute what they saw. last_seen only moves forward, so a
// replica with a slow clock cannot make a key look older than it is.
func (q *Queries) UpsertEventSample(ctx context.Context, arg UpsertEventSampleParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventSample,
		arg.Kind,
		arg.Key,
		arg.Value,
		arg.SeenCount,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
