// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_flows.sql

package sqlitedb

import (
	"context"
	"time"
)

const createLoginFlow = `-- name: CreateLoginFlow :exec
INSERT INTO login_flows (state, verifier, nonce, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateLoginFlowParams struct {
	State     string
	Verifier  string
	Nonce     string
	ExpiresAt time.Time
}

func (q *Queries) CreateLoginFlow(ctx context.Context, arg CreateLoginFlowParams) error {
	_, err := q.db.ExecContext(ctx, createLoginFlow,
		arg.State,
		arg.Verifier,
		arg.Nonce,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredLoginFlows = `-- name: DeleteExpiredLoginFlows :exec
DELETE FROM login_flows WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredLoginFlows(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLoginFlows, expiresAt)
	return err
}

const takeLoginFlow = `-- name: TakeLoginFlow :one
DELETE FROM login_flows
WHERE state = ?
RETURNING state, verifier, nonce, expires_at
`

// TakeLoginFlow redeems a state once: the row is gone whether or not it had
// expired, so a replayed callback finds nothing.
func (q *Queries) TakeLoginFlow(ctx context.Context, state string) (LoginFlow, error) {
	row := q.db.QueryRowContext(ctx, takeLoginFlow, state)
	var i LoginFlow
	err := row.Scan(
		&i.State,
		&i.Verifier,
		&i.Nonce,
		&i.ExpiresAt,
	)
	return i, err
}
