// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const deleteBrokerTokensForSubject = `-- name: DeleteBrokerTokensForSubject :exec
DELETE FROM broker_tokens
WHERE session_id IN (SELECT id FROM sessions WHERE subject = ?1)
`

func (q *Queries) DeleteBrokerTokensForSubject(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, deleteBrokerTokensForSubject, subject)
	return err
}

const deleteSessionsForSubject = `-- name: DeleteSessionsForSubject :exec
DELETE FROM sessions WHERE subject = ?1
`

func (q *Queries) DeleteSessionsForSubject(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForSubject, subject)
	return err
}

const getUser = `-- name: GetUser :one
SELECT subject, source, name, email, roles, idp_groups, first_seen, last_seen, disabled_at, disabled_by, object_id
FROM users
WHERE subject = ?1
`

func (q *Queries) GetUser(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, subject)
	var i User
	err := row.Scan(
		&i.Subject,
		&i.Source,
		&i.Name,
		&i.Email,
		&i.Roles,
		&i.IdpGroups,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DisabledAt,
		&i.DisabledBy,
		&i.ObjectID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT subject, source, name, email, roles, idp_groups, first_seen, last_seen, disabled_at, disabled_by, object_id
FROM users
WHERE CAST(?1 AS TEXT) = ''
	OR lower(subject) LIKE ?1
	OR lower(name) LIKE ?1
	OR lower(email) LIKE ?1
ORDER BY lower(name), subject
LIMIT CAST(?2 AS BIGINT)
`

type ListUsersParams struct {
	Pattern string
	MaxRows int64
}

// pattern is a lower-cased LIKE pattern; its % and _ stay wildcards.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Pattern, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Subject,
			&i.Source,
			&i.Name,
			&i.Email,
			&i.Roles,
			&i.IdpGroups,
			&i.FirstSeen,
			&i.LastSeen,
			&i.DisabledAt,
			&i.DisabledBy,
			&i.ObjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
UPDATE users
SET disabled_at = ?1, disabled_by = ?2
WHERE subject = ?3
`

type SetUserDisabledParams struct {
	DisabledAt sql.NullTime
	DisabledBy string
	Subject    string
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserDisabled, arg.DisabledAt, arg.DisabledBy, arg.Subject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (subject, source, name, email, roles, idp_groups, first_seen, last_seen, object_id)
VALUES (?1, ?2, ?3, ?4, ?5,
	?6, ?7, ?7, ?8)
ON CONFLICT (subject) DO UPDATE SET
	source     = excluded.source,
	name       = excluded.name,
	email      = excluded.email,
	roles      = excluded.roles,
	idp_groups = excluded.idp_groups,
	last_seen  = excluded.last_seen,
	-- A sign-in without the claim keeps the id an earlier one recorded.
	object_id  = CASE WHEN excluded.object_id = '' THEN users.object_id ELSE excluded.object_id END
`

type UpsertUserParams struct {
	Subject   string
	Source    string
	Name      string
	Email     string
	Roles     string
	IdpGroups string
	SeenAt    time.Time
	ObjectID  string
}

// A sign-in refreshes what the provider says; first_seen and the disabled
// state are kept.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.Subject,
		arg.Source,
		arg.Name,
		arg.Email,
		arg.Roles,
		arg.IdpGroups,
		arg.SeenAt,
		arg.ObjectID,
	)
	return err
}
