// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_endpoints.sql

package sqlitedb

import (
	"context"
	"time"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :exec
INSERT INTO webhook_endpoints (id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWebhookEndpointParams struct {
	ID            string
	TeamSlug      string
	ChannelSlug   string
	DestinationID string
	TokenHash     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, createWebhookEndpoint,
		arg.ID,
		arg.TeamSlug,
		arg.ChannelSlug,
		arg.DestinationID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = ?
`

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWebhookEndpoint, id)
	return err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at
FROM webhook_endpoints
WHERE id = ?
`

func (q *Queries) GetWebhookEndpoint(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpoint, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamSlug,
		&i.ChannelSlug,
		&i.DestinationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointBySlug = `-- name: GetWebhookEndpointBySlug :one
SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at
FROM webhook_endpoints
WHERE team_slug = ? AND channel_slug = ?
`

type GetWebhookEndpointBySlugParams struct {
	TeamSlug    string
	ChannelSlug string
}

// GetWebhookEndpointBySlug is the request path, turned into a row. It is the
// only lookup a sender can reach, so it matches on the pair alone and leaves
// the token to a constant-time comparison outside SQL.
func (q *Queries) GetWebhookEndpointBySlug(ctx context.Context, arg GetWebhookEndpointBySlugParams) (WebhookEndpoint, error) {
	row := q.db.QueryRowContext(ctx, getWebhookEndpointBySlug, arg.TeamSlug, arg.ChannelSlug)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamSlug,
		&i.ChannelSlug,
		&i.DestinationID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, team_slug, channel_slug, destination_id, token_hash, created_at, updated_at
FROM webhook_endpoints
ORDER BY team_slug, channel_slug
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context) ([]WebhookEndpoint, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookEndpoint
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TeamSlug,
			&i.ChannelSlug,
			&i.DestinationID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWebhookEndpointToken = `-- name: RotateWebhookEndpointToken :exec
UPDATE webhook_endpoints
SET token_hash = ?, updated_at = ?
WHERE id = ?
`

type RotateWebhookEndpointTokenParams struct {
	TokenHash string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) RotateWebhookEndpointToken(ctx context.Context, arg RotateWebhookEndpointTokenParams) error {
	_, err := q.db.ExecContext(ctx, rotateWebhookEndpointToken, arg.TokenHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :exec
UPDATE webhook_endpoints
SET team_slug = ?, channel_slug = ?, destination_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateWebhookEndpointParams struct {
	TeamSlug      string
	ChannelSlug   string
	DestinationID string
	UpdatedAt     time.Time
	ID            string
}

// The token is written by its own statement, so editing an endpoint cannot
// silently rotate the secret the sender is using.
func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookEndpoint,
		arg.TeamSlug,
		arg.ChannelSlug,
		arg.DestinationID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
